name: Model Deployment

on:
  push:
    branches: [terraform]
    
  workflow_call:
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS:
        required: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: itesm-mlops
            # Add "id-token" with the intended permissions.
        permissions:
          contents: 'read'
          id-token: 'write'
        
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v1'
          with:
            credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_wrapper: false
    
        - name: Configure Google Cloud credentials
          uses: google-github-actions/setup-gcloud@v1
    
        - name: Terraform Init
          run: terraform init
          working-directory: terraform
    
        - name: Terraform Plan
          run: terraform plan
          working-directory: terraform
    
        - name: Terraform Apply
          run: terraform apply -auto-approve
          working-directory: terraform